# Generated by Django 5.0.6 on 2026-08-08 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('private_spaces', '0001_initial'),
        ('workspaces', '0002_channelmember_channelrole_userchannelrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('direct_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_spaces.directchat')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_spaces.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_messages', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspaces.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messaging.basemessage')),
                ('is_edited', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sent_at', 'id'),
            },
            bases=('messaging.basemessage',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_media/%Y/%m/%d')),
                ('file_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='messaging.basemessage')),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('base_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.basemessage')),
            ],
            options={
                'ordering': ('edited_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='basemessage',
            index=models.Index(fields=['topic', 'id'], name='messaging_topic_message_idx'),
        ),
        migrations.AddIndex(
            model_name='basemessage',
            index=models.Index(fields=['group', 'id'], name='messaging_group_message_idx'),
        ),
        migrations.AddIndex(
            model_name='basemessage',
            index=models.Index(fields=['direct_chat', 'id'], name='messaging_dm_message_idx'),
        ),
        migrations.AddConstraint(
            model_name='basemessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('direct_chat__isnull', True), ('group__isnull', True), ('topic__isnull', False)), models.Q(('direct_chat__isnull', True), ('group__isnull', False), ('topic__isnull', True)), models.Q(('direct_chat__isnull', False), ('group__isnull', True), ('topic__isnull', True)), _connector='OR'), name='messaging_exactly_one_target'),
        ),
    ]
