# Generated by Django 5.0.6 on 2026-08-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "basemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="messaging.basemessage",
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
            ],
            options={
                "ordering": ("scheduled_time", "id"),
            },
            bases=("messaging.basemessage",),
        ),
    ]
