# Generated by Django 5.0.6 on 2026-08-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_scheduledmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="message_media_thumbnails/%Y/%m/%d"
            ),
        ),
    ]
