# Generated by Django 5.0.6 on 2026-08-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_scrum_37_message_models"),
        ("private_spaces", "0001_initial"),
        ("workspaces", "0002_channelmember_channelrole_userchannelrole_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["topic", "basemessage_ptr"], name="messaging_topic_message_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["group", "basemessage_ptr"], name="messaging_group_message_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["direct_chat", "basemessage_ptr"],
                name="messaging_dm_message_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["topic", "basemessage_ptr"],
                name="messaging_topic_scheduled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["group", "basemessage_ptr"],
                name="messaging_group_scheduled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["direct_chat", "basemessage_ptr"],
                name="messaging_dm_scheduled_idx",
            ),
        ),
    ]
