# Generated by Django 5.0.6 on 2026-07-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("users", "0002_copy_existing_user_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="allow_group_invitations",
        ),
    ]
